export {default as Error} from "./ZZMisc/Error";
export {default as Login} from "./Login/Login";
export {default as Signup} from "./Signup/Signup";
export {default as Home} from "./Home/Home";
export { default as ProductsHome } from './Products/ProductsHome';
export { default as Products } from './Products/Products';
export { default as ProductView } from './Products/ProductView';
export { default as ProductEdit } from './Products/ProductEdit';
export { default as ProductCreate } from './Products/ProductCreate';
export { default as ProducersHome } from './Producers/ProducersHome';
export { default as Producers } from './Producers/Producers';
export { default as ProducerView } from './Producers/ProducerView';
export { default as ProducerEdit } from './Producers/ProducerEdit';
export { default as ProducerCreate } from './Producers/ProducerCreate';
export { default as CategoriesHome } from './Categories/CategoriesHome';
export { default as Categories } from './Categories/Categories';
export { default as CategoryView } from './Categories/CategoryView';
export { default as CategoryEdit } from './Categories/CategoryEdit';
export { default as CategoryCreate } from './Categories/CategoryCreate';
export { default as AdminsHome } from './Admin/AdminsHome';
export { default as Admins } from './Admin/Admins';
export { default as AdminCreate } from './Admin/AdminCreate';
export { default as AdminView } from './Admin/AdminView';
export { default as AdminEdit } from './Admin/AdminEdit';

// export {default as Profile} from "./Profile/Profile";
// export {default as ProfileView} from "./Profile/ProfileView";
// export {default as ProfileEdit} from "./Profile/ProfileEdit";
// export {default as Cart} from "./Cart/Cart";
// export { default as Products } from './Products/Products';
// export { default as FeaturedProducts } from './Products/FeaturedProducts';
// export { default as ProductView } from './Products/ProductView';
// export { default as Dashboard } from './Dashboard/Dashboard';